---
name: Push
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/inko:latest
    steps:
      - run: microdnf install --quiet --assumeyes tar git
      - uses: actions/checkout@v4
      - name: Configuring Git
        run: |
          git config --global user.email git@example.com
          git config --global user.name git
      - run: inko --version
      - run: inko pkg sync
      - run: inko test
